{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orchestrator-api-local
  namespace: {{ include "stream-orchestrator.orchestratorNamespace" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.api }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: orchestrator-api
                port:
                  number: 8080
    - host: {{ .Values.ingress.hosts.dashboard }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dashboard
                port:
                  number: 8080
    - host: {{ .Values.ingress.hosts.rabbitmq }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: rabbitmq
                port:
                  number: 15672
    - host: {{ .Values.ingress.hosts.streamGateway }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: stream-gateway
                port:
                  number: 8081
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: monitoring-local
  namespace: {{ include "stream-orchestrator.monitoringNamespace" . }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.hosts.grafana }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: grafana
                port:
                  number: 3000
    - host: {{ .Values.ingress.hosts.prometheus }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: prometheus
                port:
                  number: 9090
{{- end }}

