{{- $dbUrl := include "stream-orchestrator.dbUrl" . -}}
{{- $rabbitmqUrl := include "stream-orchestrator.rabbitmqUrl" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-secrets
  namespace: {{ include "stream-orchestrator.orchestratorNamespace" . }}
type: Opaque
stringData:
  {{- if $dbUrl }}
  DB_URL: {{ $dbUrl | quote }}
  {{- end }}
  {{- if $rabbitmqUrl }}
  RABBITMQ_URL: {{ $rabbitmqUrl | quote }}
  {{- end }}
  MEDIAMTX_CONTROL_USERNAME: {{ .Values.secrets.mediamtxControlUsername | quote }}
  MEDIAMTX_CONTROL_PASSWORD: {{ .Values.secrets.mediamtxControlPassword | quote }}
