apiVersion: v1
kind: ServiceAccount
metadata:
  name: instance-reconciler
  namespace: orchestrator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: instance-reconciler-pod-reader
  namespace: streaming
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: instance-reconciler-pod-reader
  namespace: streaming
subjects:
  - kind: ServiceAccount
    name: instance-reconciler
    namespace: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: instance-reconciler-pod-reader
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instance-reconciler-node-reader
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: instance-reconciler-node-reader
subjects:
  - kind: ServiceAccount
    name: instance-reconciler
    namespace: orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: instance-reconciler-node-reader
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: instance-reconciler
  namespace: orchestrator
  labels:
    app: instance-reconciler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: instance-reconciler
  template:
    metadata:
      labels:
        app: instance-reconciler
    spec:
      serviceAccountName: instance-reconciler
      containers:
        - name: instance-reconciler
          image: agj017/funnel-instance-reconciler:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: orchestrator-config
          env:
            - name: DB_URL
              valueFrom:
                secretKeyRef:
                  name: orchestrator-secrets
                  key: DB_URL
