apiVersion: v1
kind: ConfigMap
metadata:
  name: mediamtx-config
  namespace: streaming
  labels:
    app: mediamtx
data:
  mediamtx.yml: |
    logLevel: info
    logDestinations: [stdout]
    logStructured: false

    authMethod: internal
    authInternalUsers:
      - user: any
        pass:
        ips: []
        permissions:
          - action: publish
          - action: read
          - action: playback
          - action: api
          - action: metrics

    api: true
    apiAddress: :9997
    apiAllowOrigins: ['*']

    metrics: true
    metricsAddress: :9998
    metricsAllowOrigins: ['*']

    rtsp: true
    rtspTransports: [tcp]
    rtspAddress: :8554

    hls: true
    hlsAddress: :8888

    paths:
      all_others:
        source: publisher
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mediamtx
  namespace: streaming
  labels:
    app: mediamtx
spec:
  serviceName: mediamtx-headless
  replicas: 3
  selector:
    matchLabels:
      app: mediamtx
  template:
    metadata:
      labels:
        app: mediamtx
    spec:
      containers:
        - name: mediamtx
          image: bluenviron/mediamtx:1.18.2
          imagePullPolicy: IfNotPresent
          ports:
            - name: rtsp
              containerPort: 8554
            - name: hls
              containerPort: 8888
            - name: api
              containerPort: 9997
            - name: metrics
              containerPort: 9998
          volumeMounts:
            - name: config
              mountPath: /mediamtx.yml
              subPath: mediamtx.yml
              readOnly: true
          # readinessProbe:
          #   httpGet:
          #     path: /v3/config/global/get
          #     port: api
          #   initialDelaySeconds: 3
          #   periodSeconds: 5
          # livenessProbe:
          #   httpGet:
          #     path: /v3/config/global/get
          #     port: api
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: mediamtx-config
---
apiVersion: v1
kind: Service
metadata:
  name: mediamtx-headless
  namespace: streaming
  labels:
    app: mediamtx
spec:
  clusterIP: None
  selector:
    app: mediamtx
  ports:
    - name: rtsp
      port: 8554
      targetPort: rtsp
    - name: hls
      port: 8888
      targetPort: hls
    - name: api
      port: 9997
      targetPort: api
    - name: metrics
      port: 9998
      targetPort: metrics
