apiVersion: v1
kind: Secret
metadata:
  name: orchestrator-secrets
  namespace: orchestrator
type: Opaque
stringData:
  DB_URL: postgres://postgres:postgres@postgresql.orchestrator.svc.cluster.local:5432/stream_orchestrator?sslmode=disable
  RABBITMQ_URL: amqp://guest:guest@rabbitmq.orchestrator.svc.cluster.local:5672/
  MEDIAMTX_CONTROL_USERNAME: ""
  MEDIAMTX_CONTROL_PASSWORD: ""
